### ISSUE TITLE
Crash when entering Tematy

### ISSUE THREAD

**Issue by LonguCodes** [oxygensend/learning_logs#1]
### When

Registered and went to `Tematy`

![image](https://user-images.githubusercontent.com/48600606/156645532-90ca105e-c741-4ca2-b772-f5be8b63d779.png)

**Comment by oxygensend** [comment]
### Fixed

Unfortunately i restarted whole server and database, so your account is gone, sorry for that XD because I couldn't find the reason of that. Thanks for info that debug-info is also visible.
